from dotenv import dotenv_values
env = dotenv_values(".env")

MYSQL_DIALECT = env["MYSQL_DIALECT"]
MYSQL_DRIVER = env["MYSQL_DRIVER"]
MYSQL_HOST = env["MYSQL_HOST"]
MYSQL_USER = env["MYSQL_USER"]
MYSQL_PASSWORD = env["MYSQL_PASSWORD"]
MYSQL_PORT = env["MYSQL_PORT"]
MYSQL_PROD_DB = env["MYSQL_PROD_DB"]
MYSQL_DEV_DB = env["MYSQL_DEV_DB"]
MYSQL_TEST_DB = env["MYSQL_TEST_DB"]

ANSI_BLACK = "\033[30m"
ANSI_RED = "\033[31m"
ANSI_GREEN = "\033[32m"
ANSI_YELLOW = "\033[33m"
ANSI_BLUE = "\033[34m"
ANSI_MAGENTA = "\033[35m"
ANSI_CYAN = "\033[36m"
ANSI_WHITE = "\033[37m"
ANSI_RESET = "\033[0m"

INITIAL_BUDGET=10000.00